version: '3.8'

services:
  start-page:
    container_name: excalith-start-page
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - data:/app/data

volumes:
  data:
    name: excalith-start-page